server:
  port: 7777
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
  server:
    evictionIntervalTimerInMs: 1000
